version: STgram-MFN
description: STgram-MFN
time_version: False # if set ture, add time information in version
save_version_files: False # if set true, save each version files in runs
save_version_file_patterns:
  - "*.py"
  - "*.yaml"
pass_dirs:
  - '.'
  - '_'
  - 'runs'
  - 'results'

# filepath
train_dirs:
  - ../data/dataset/fan/train
  - ../data/dataset/pump/train
  - ../data/dataset/slider/train
  - ../data/dataset/ToyCar/train
  - ../data/dataset/ToyConveyor/train
  - ../data/dataset/valve/train

test_dirs:
  - ../data/dataset/fan/test
  - ../data/dataset/pump/test
  - ../data/dataset/slider/test
  - ../data/dataset/ToyCar/test
  - ../data/dataset/ToyConveyor/test
  - ../data/dataset/valve/test

result_dir: ./results

# audio preprocess
sr: 16000
n_fft: 1024
n_mels: 128
win_length: 1024
hop_length: 512
power: 2.0
secs: 10

cuda: True
# train
random_seed: 42
epochs: 300
# epochs: 200
batch_size: 128
num_workers: 24
lr: 1e-4
device_ids:
  # - 0
  - 1
valid_every_epochs: 5
early_stop_epochs: -1
start_save_model_epochs: 300
save_model_interval_epochs: 1
start_scheduler_epoch: 20
start_valid_epoch: 0

# loss
use_arcface: True
m: 0.7
s: 30

# test
load_epoch: False # it will test your model if set a value, e.g. best, 10, 100

